config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :channels do
    member do
      post :leave
    end
  end
  
  root to: "channels#index"

  resources :messages, only: [:create]
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :user_channels
  has_many :users, through: :user_channels
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  def index
    @channels = Channel.all
    @admin = current_user.admin?
  end

  def new
    @channel = Channel.new
  end

  def create
    if Channel.create!(channel_params)
      flash[:success]= t('create.success', record: "channel")
    else
      flash[:error]= t('create.error', record: "channel")
    end
    redirect_to root_path
  end

  def update
    if @channel.update!(channel_params)
      flash[:success]= t('update.success', record: "channel")
    else
      flash[:error]= t('update.error', record: "channel")
    end
    redirect_to channel_path(@channel)
  end

  def destroy
    if @channel.destroy!
      flash[:success]= t('destroy.success', record: "channel")
    else
      flash[:error]= t('destroy.error', record: "channel")
    end
    redirect_to root_path
  end

  def edit
  end

  def show
    raise "Invalid user ID" if params[:user_id].to_i != current_user.id
    uc = UserChannel.find_or_create_by!(channel_id: params[:id], user_id: params[:user_id])
    @messages = Message.where(channel_id: @channel.id).where('created_at >= ?', uc.created_at)
  end

  def leave
    UserChannel.find_by(channel_id: params[:id], user_id: params[:user_id])
    redirect_to root_path
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit!
  end
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/views/channels/_form.html.haml
= form_with model: @channel do |f|
  .form-group
    = f.label :name
    = f.text_field :name, required: true, class: "form-control"

  .form-group
    = f.label :description
    = f.text_field :description, required: true, class: "form-control"

  .form-group
    = f.submit "Create channel", { class: 'btn btn-primary' }

app/views/channels/edit.html.haml
%h1 Edit channel
= render partial: "form"

app/views/channels/index.html.haml
.row
  .col-10
    %h2 Channels
  - if @admin
    .col-2
      .float-right
        = link_to "Create Channel", new_channel_path, class: "btn btn-primary btn-sm mt-2"

%table.table
  %thead
    %tr
      %th #
      %th Name
      %th Description
      %th
  %tbody
    - @channels.each.with_index(1) do |channel, index|
      %tr
        %th= index
        %td= link_to channel.name, channel_path(channel, user_id: current_user.id)
        %td= channel.description
        %td
          - if @admin
            = link_to "Edit", edit_channel_path(channel)
            = link_to "Delete", channel_path(channel), method: :delete, class: "pl-3"

app/views/channels/new.html.haml
%h1 New Channel
= render partial: "form"

app/views/channels/show.html.erb
<h1>Channel#show</h1>
<p>Find me in app/views/channel/show.html.erb</p>

app/views/channels/show.html.haml
.channel_container{"data-channel-id" => @channel.id}

.row
  .col-10
    %h2= @channel.name
    %p= @channel.description
  .col-2
    = link_to "Leave channel", leave_channel_path, method: :post, class: 'btn btn-primary'


%h3 Chat
.card.p-3.m-3
  .chat-container
    - @messages.each do |message|
      .message.card.p3
        %p="#{message.user.email} (#{message.created_at.strftime("%H:%M:%S")}): #{message.text}"

%h3 Send Message
.card.p-3.m-3
  = form_with model: Message.new, class: 'send-message' do |f|
    = f.hidden_field :user_id, {value: current_user.id }
    = f.hidden_field :channel_id, {value:  @channel.id }

    .form-group
      = f.label :text
      = f.text_field :text, required: true, class: "form-control"

    .form-group
      = f.submit "Send message", { class: 'btn btn-primary btn-sm mt-2' }